version: '3'

services:
  pouledb:
    image: postgres:10-alpine
    hostname: pouledb
    container_name: pouledb
    environment:
      POSTGRES_PASSWORD: Doelpunt1!
      POSTGRES_USER: MarcoVanBasten
      POSTGRES_DB: poule
    volumes:
      - pgdata_poule:/var/lib/postgresql/data
     
  pouleweb:
    image: poule
    restart: unless-stopped
    links:
      - pouledb
    ports:
      - 5000:80
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POULE_SEED_USER_PASSWORD: ${POULE_SEED_USER_PASSWORD}
      POULE_SMTP_USER_PASSWORD: ${POULE_SMTP_USER_PASSWORD}
volumes:
  pgdata_poule:
