version: '3'

services:
  pouledb-dev:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Goal1!
      POSTGRES_USER: RobinVanPersie
      POSTGRES_DB: poule-dev

  redis:
   image: "redis"
   hostname: "redis"
   ports:
     - "6379:6379"